namespace FoosballApi.Models.Cms
{
    public class HardcodedStrings
    {
        public string matches { get; set; }
        public string newGame { get; set; }
        public string quickActions { get; set; }
        public string lastTenMatches { get; set; }
        public string statistics { get; set; }
        public string history { get; set; }
        public string leagues { get; set; }
        public string pricing { get; set; }
        public string settings { get; set; }
        public string about { get; set; }
        public string logout { get; set; }
        public string language { get; set; }
        public string darkTheme { get; set; }
        public string lightTheme { get; set; }
        public string changePassword { get; set; }
        public string enableNotifications { get; set; }
        public string common { get; set; }
        public string security { get; set; }
        public string selectLanguage { get; set; }
        public string islenska { get; set; }
        public string svenska { get; set; }
        public string won { get; set; }
        public string lost { get; set; }
        public string scored { get; set; }
        public string recieved { get; set; }
        public string goals { get; set; }
        public string user { get; set; }
        public string username { get; set; }
        public string organisation { get; set; }
        public string personalInformation { get; set; }
        public string integration { get; set; }
        public string slack { get; set; }
        public string discord { get; set; }
        public string matchDetails { get; set; }
        public string totalPlayingTime { get; set; }
        public string newMatch { get; set; }
        public string rematch { get; set; }
        public string twoPlayers { get; set; }
        public string fourPlayers { get; set; }
        public string choosePlayers { get; set; }
        public string match { get; set; }
        public string startGame { get; set; }
        public string chooseTeammate { get; set; }
        public string chooseOpponent { get; set; }
        public string chooseOpponents  { get; set; }
        public string matchReport { get; set; }
        public string game { get; set; }
        public string resume { get; set; }
        public string pause { get; set; }
        public string close { get; set; }
        public string yes { get; set; }
        public string no { get; set; }
        public string cancel { get; set; }
        public string areYouSureAlert { get; set; }
        public string currentOrganisation { get ; set; }
        public string organisations { get; set; }
        public string players { get; set; }
        public string newOrganisation { get; set; }
        public string addPlayers { get; set; }
        public string nameOfNewOrganisation { get; set; }
        public string create { get; set; }
        public string newOrganisationSuccessMessage { get; set; }
        public string newOrganisationErrorMessage { get; set; }
        public string organisationSettings { get; set; }
        public string createNewOrganisation { get; set; }
        public string joinExistingOrganisation { get; set; }
        public string managePlayers { get; set; }
        public string changeOrganisation { get; set; }
        public string information { get; set; }
        public string organisationCode { get; set; }
        public string letOtherPlayersJoinYourOrganisation { get; set; }
        public string joinOrganisation { get; set; }
        public string scanQrCode { get; set; }
        public string success { get; set; }
        public string failure { get; set; }
        public string obsFailure { get; set; }
        public string cameraPermissionWasDenied { get; set; }
        public string unknownError { get; set; }
        public string youPressedTheBackButton { get; set; }
        public string joinOrganisationInfo { get; set; }
        public string joinOrganisationInfo2 { get; set; }
        public string actions { get; set; }
        public string joinExistingOrganisationWithQrCode { get; set; }
        public string organisationCardInfo { get; set; }
        public string managePlayer { get; set; }
        public string admin { get; set; }
        public string deleteUser { get; set; }
        public string active { get; set; }
        public string inactive { get; set; }
        public string changeOrganisationAlertText { get; set; }
        public string deleteThisMatch { get; set; }
        public string deleteMatchAreYouSure { get; set; }
        public string createGroupPlayer { get; set; }
        public string groupPlayerInfoText { get; set; }
        public string groupPlayerCreateFailure { get; set; }
        public string groupPlayerCreateSuccess { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string league { get; set; } 
        public string createNewLeague { get; set; } 
        public string createLeague { get; set; } 
        public string leagueName { get; set; }
        public string standings { get; set; }
        public string fixtures { get; set; }
        public string notStarted { get; set; }
        public string welcomeTextBody { get; set; }
        public string welcomeTextButton { get; set; }
        public string welcomeTextHeadline { get; set; }
        public string noUsersExists { get; set; }
    }
}